import type { DashboardViewData } from "./dashboard-types";

export function emptyDashboardViewData(): DashboardViewData {
  const today = new Date().toISOString().slice(0, 10);
  return {
    audit: {
      through: today,
      householdFundedCents: 0,
      grossReceiptTotalCents: 0,
      externalFundingCents: 0,
      transactionCount: 0,
      warehouseTransactionCount: 0,
      gasTransactionCount: 0,
      opticalTransactionCount: 0,
      averageWarehouseCents: 0,
      reconciliationIssueCount: 0,
    },
    months: [],
    channels: [
      {
        key: "warehouse",
        label: "Warehouse",
        color: "var(--sage)",
        householdFundedCents: 0,
        grossReceiptTotalCents: 0,
        transactionCount: 0,
      },
      {
        key: "gas",
        label: "Gas",
        color: "var(--apricot)",
        householdFundedCents: 0,
        grossReceiptTotalCents: 0,
        transactionCount: 0,
      },
      {
        key: "optical",
        label: "Optical out-of-pocket",
        color: "var(--lilac)",
        householdFundedCents: 0,
        grossReceiptTotalCents: 0,
        transactionCount: 0,
      },
    ],
    productCategories: [],
    warehouseTaxCents: 0,
    classifiedWarehouseCents: 0,
    needsReviewWarehouseCents: 0,
    transactions: [],
    receiptLines: [],
    recentTransactions: [],
    products: [],
    suggestions: [],
    suggestionPlanDate: today,
    latestWarehouseTransaction: {
      id: "empty-dashboard",
      purchasedOn: today,
      channel: "warehouse",
      itemCount: 0,
      receiptTotalCents: 0,
      householdFundedCents: 0,
      discountCents: 0,
      merchandiseSubtotalCents: 0,
      taxCents: 0,
      externalFundingCents: 0,
      sourceType: "receipt_photo",
      purchaseContext: "trip",
      auditFlag: "none",
    },
  };
}
